pygments:   true
markdown:   maruku
url: "bytespider.github.com/jsOAuth-Twitter"
navigation:
  - text: "Getting started"
    url: "/"
  - text: "API Reference"
    url: "/api-reference"
api_navigation:
  - text: "Core"
    items:
      - text: "OAuth.Twitter"
        url: "/api-reference/oauth-twitter"
      - text: "authenticate"
        url: "/api-reference/authenticate"
      - text: "deauthenticate"
        url: "/api-reference/deauthenticate"
      - text: "varifyCredentials"
        url: "/api-reference/varify-credentials"
package_version: 0.1.0