pygments:   true
markdown:   maruku
url: "bytespider.github.com/jsOAuth-Twitter"
navigation:
  - text: "Getting started"
    url: "/"
  - text: "API Reference"
    url: "/api-reference"
    subnavigation:
      - text: "OAuth.Twitter"
        url: "/api-reference/OAuth-Twitter"
package_version: 0.1.0