pygments:   true
markdown:   maruku
url: "bytespider.github.com/jsOAuth-Twitter"
navigation:
  - text: "Getting started"
    url: "/"
  - text: "API Reference"
    url: "/api-reference"
api_navigation:
  - text: "Initialisation"
    items:
      - text: "OAuth.Twitter"
        url: "/api-reference/oauth-twitter.html"
  - text: "Authentication"
    items:
      - text: "authenticate"
        url: "/api-reference/authenticate.html"
      - text: "deauthenticate"
        url: "/api-reference/deauthenticate.html"
  - text: "Timelines"
    items:
      - text: "homeTimeline"
        url: "/api-reference/homeTimeline.html"
      - text: "userTimeline"
        url: "/api-reference/userTimeline.html"
      - text: "publicTimeline"
        url: "/api-reference/publicTimeline.html"
  - text: "Tweeting"
    items:
      - text: "varifyCredentials"
        url: "/api-reference/varifyCredentials"
package_version: 0.1.0